services:
  service1:
    build: ./service1
    depends_on:
      - service2      
    links:      
      - statsd
    ports:
      - "8000:8000"
    environment:
      APP_NAME: service1
      OTEL_AGENT: otel-agent
    volumes:
      - ./config/gunicorn/config.py:/gunicorn_config.py
  service2:
    build: ./service2
    depends_on:
      - db
    links:
      - db
      - statsd
    environment:
      APP_NAME: service2
      OTEL_AGENT: otel-agent 
    volumes:
      - ./config/gunicorn/config.py:/gunicorn_config.py
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: service2
      MYSQL_USER: joe
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
  statsd:
    image: prom/statsd-exporter
    container_name: statsd
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    links:
      - statsd
    volumes:
      - ./config/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090