services:  
  otel-agent:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-agent-config.yml"]
    volumes:
      - ./otel-agent-config.yml:/etc/otel-agent-config.yml
    links:
      - otel-collector
    depends_on:
      - otel-collector  
  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
    depends_on:
      - jaeger-all-in-one
    links:
      - jaeger-all-in-one
  jaeger-all-in-one:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "14268:14268"
      - "6831:6831/udp"
  client:
    links:
      - service1
    depends_on:
      - service1
    build:
      context: ./
      dockerfile: Dockerfile-client